#	V I S U A L I S A T I O N
#/vis/open OGLSX
/vis/viewer/set/viewpointThetaPhi 60 60
/vis/viewer/zoom 1.5
/vis/drawVolume
#/vis/viewer/flush
#/tracking/verbose 0
/tracking/storeTrajectory 1
/vis/scene/add/trajectories 
/vis/scene/endOfEventAction accumulate

/vis/disable

/gate/geometry/setMaterialDatabase /home/ratcap/Simulation/gate/gate_v7.1/GateMaterials.db

#     W O R L D
/gate/world/geometry/setXLength 30. cm
/gate/world/geometry/setYLength 30. cm
/gate/world/geometry/setZLength 30. cm

/gate/world/daughters/name cylindricalPET
/gate/world/daughters/insert cylinder
/gate/cylindricalPET/setMaterial Air
/gate/cylindricalPET/geometry/setRmax 102.85 mm
/gate/cylindricalPET/geometry/setRmin 67.3 mm
/gate/cylindricalPET/geometry/setHeight 114.7 mm
#/gate/cylindricalPET/vis/forceWireframe
#/gate/geometry/rebuild

#     R S E C T O R : You define your block detection unit
#
/gate/cylindricalPET/daughters/name rsector
/gate/cylindricalPET/daughters/insert box

/gate/rsector/placement/setTranslation 85.0 0 0 mm
/gate/rsector/geometry/setXLength 14.0 mm 
/gate/rsector/geometry/setYLength 12 mm
/gate/rsector/geometry/setZLength 12 mm
/gate/rsector/setMaterial Air
#/gate/rsector/vis/forceWireframe
#/gate/geometry/rebuild


#ZOOM
#/vis/viewer/panTo 40 -40 mm
#/vis/viewer/zoom 4

#/gate/geometry/rebuild

#	C R Y S T A L : in your block detection unit !
#
/gate/rsector/daughters/name crystal
/gate/rsector/daughters/insert box
/gate/crystal/geometry/setXLength 14. mm
/gate/crystal/geometry/setYLength 1.5 mm
/gate/crystal/geometry/setZLength 1.5 mm
/gate/crystal/setMaterial Water
#/gate/crystal/vis/setColor red
#/gate/crystal/vis/forceWireframe

#/gate/geometry/rebuild


# L A Y E R 
/gate/crystal/daughters/name LSO 
/gate/crystal/daughters/insert box 
/gate/LSO/geometry/setXLength 14. mm 
/gate/LSO/geometry/setYLength 1.5 mm 
/gate/LSO/geometry/setZLength 1.5 mm 
#/gate/LSO/placement/setTranslation 0 0 0 mm 
/gate/LSO/setMaterial LYSO
#/gate/LSO/vis/setColor yellow




#	R E P E A T    C R Y S T A L   I N    Y O U R     B L O C K
/gate/crystal/repeaters/insert cubicArray
/gate/crystal/cubicArray/setRepeatNumberX 1
/gate/crystal/cubicArray/setRepeatNumberY 8
/gate/crystal/cubicArray/setRepeatNumberZ 8
/gate/crystal/cubicArray/setRepeatVector 0. 1.5 1.5 mm

#/gate/geometry/rebuild

#	R E P E A T    Y O U R     B L O C K   (R S E C T O R)  I N    Y O U R    C Y L I N D R I C A L 1    S Y S T E M
/gate/rsector/repeaters/insert ring
#/gate/rsector/ring/setFirstAngle 7.5 deg
/gate/rsector/ring/setRepeatNumber 40

#/gate/geometry/rebuild

/gate/rsector/repeaters/insert linear
/gate/rsector/linear/setRepeatNumber 4
/gate/rsector/linear/setRepeatVector 0. 0. 13.5 mm  #11.2 mm

#/gate/geometry/rebuild

#	A T T A C H    S Y S T E M :                                               definition of your global detector
/gate/systems/cylindricalPET/rsector/attach rsector
/gate/systems/cylindricalPET/crystal/attach crystal
/gate/systems/cylindricalPET/layer0/attach LSO                                      #do we need this layer? must be layer0

#	A T T A C H    L A Y E R  SD : definition of your sensitive detector
/gate/LSO/attachCrystalSD                                                          #so does this become /gate/crystal?
/gate/systems/cylindricalPET/describe


####phantom######                                                                  no phantom in this simulation

#/gate/world/daughters/name phantom1
#/gate/world/daughters/insert cylinder
#/gate/phantom1/setMaterial Water
#/gate/phantom1/vis/forceWireframe
#/gate/phantom1/vis/setColor blue
#/gate/phantom1/placement/setTranslation 0.5 0.0 7.0 cm

##/gate/geometry/rebuild

#/gate/phantom1/geometry/setRmax   60 mm
#/gate/phantom1/geometry/setHeight 100 mm

#/gate/phantom1/attachPhantomSD

#
#       P H Y S I C S
#
/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel

/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel StandardModel

/gate/physics/addProcess RayleighScattering
/gate/physics/processes/RayleighScattering/setModel PenelopeModel

/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
/gate/physics/processes/ElectronIonisation/setModel StandardModel e+
#/gate/physics/processes/ElectronIonisation/setStepFunction e- 0.2 1 km
#/gate/physics/processes/ElectronIonisation/setLinearLossLimit e- 0.1

#/gate/physics/addProcess Bremsstrahlung
#/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
#/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+

#/gate/physics/addProcess PositronAnnihilation

#/gate/physics/addProcess MultipleScattering e+
#/gate/physics/addProcess MultipleScattering e-

/gate/physics/processList Enabled
/gate/physics/processList Initialized

#
#       C U T S
#


# Cuts for particle in NEMACylinder
#/gate/physics/Gamma/SetCutInRegion      NEMACylinder 1.0 cm
#/gate/physics/Electron/SetCutInRegion   NEMACylinder 1.0 cm
#/gate/physics/Positron/SetCutInRegion   NEMACylinder 1.0 cm

# Cuts for particle in NEMACylinder
/gate/physics/Gamma/SetCutInRegion      LSO 1.0 mm
/gate/physics/Electron/SetCutInRegion   LSO 1.0 mm
/gate/physics/Positron/SetCutInRegion   LSO 1.0 mm

# Cuts for particle in NEMACylinder
#/gate/physics/Gamma/SetCutInRegion      BGO 1.0 cm
#/gate/physics/Electron/SetCutInRegion   BGO 1.0 cm
#/gate/physics/Positron/SetCutInRegion   BGO 1.0 cm


#	I N I T I A L I Z E 
/gate/run/initialize

/gate/physics/displayCuts

#	A D D E R
/gate/digitizer/Singles/insert adder


#       R E A D O U T 
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setDepth 1

# T E M P O R A L     R E S O L U T I O N
/gate/digitizer/Singles/insert timeResolution
/gate/digitizer/Singles/timeResolution/setTimeResolution 8.5732 ns   # from Sudeepti Southekal

#      E N E R G Y   B L U R R I N G
/gate/digitizer/Singles/insert blurring
/gate/digitizer/Singles/blurring/setResolution 0.1328
/gate/digitizer/Singles/blurring/setEnergyOfReference 511. keV


#       E N E R G Y   C U T
/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 350 keV
#/gate/digitizer/Singles/thresholder/setThreshold 511. keV
/gate/digitizer/Singles/insert upholder
/gate/digitizer/Singles/upholder/setUphold 1000. keV


#       D E A D    T I M E 
/gate/digitizer/Singles/insert deadtime
/gate/digitizer/Singles/deadtime/setDeadTime 80 ns
/gate/digitizer/Singles/deadtime/setMode nonparalysable
/gate/digitizer/Singles/deadtime/chooseDTVolume rsector


#	C O I N C I    S O R T E R 
/gate/digitizer/Coincidences/setWindow 8. ns  # tau = 2 * 8.5732 from MIC 09 submission for ratcap
/gate/digitizer/Coincidences/setOffset 0. ns
/gate/digitizer/Coincidences/setDepth 1
/gate/digitizer/Coincidences/describe
/gate/digitizer/Coincidences/MultiplesPolicy killAll

/gate/digitizer/name delay
/gate/digitizer/insert coincidenceSorter
/gate/digitizer/delay/setWindow 8. ns
/gate/digitizer/delay/setOffset 500. ns
/gate/digitizer/delay/describe


/gate/source/addSource twogammapoint1 gps
/gate/source/twogammapoint1/setActivity 1000000 becquerel
/gate/source/twogammapoint1/setType backtoback
/gate/source/twogammapoint1/gps/particle gamma
/gate/source/twogammapoint1/gps/energytype Mono
/gate/source/twogammapoint1/gps/monoenergy 0.511 MeV
#/gate/source/twogammapoint1/setForcedUnstableFlag true
#/gate/source/twogammapoint1/setForcedHalfLife 109 m   
#/gate/source/twogammapoint1/gps/confine NULL

/gate/source/twogammapoint1/gps/type Point
#/gate/source/twogammapoint1/gps/shape Cylinder
#/gate/source/twogammapoint1/gps/radius .05 cm 
#/gate/source/twogammapoint1/gps/halfz  .05 cm
/gate/source/twogammapoint1/gps/angtype iso

/gate/source/twogammapoint1/gps/mintheta 72 deg 
/gate/source/twogammapoint1/gps/maxtheta 108 deg 
/gate/source/twogammapoint1/gps/minphi 0. deg 
/gate/source/twogammapoint1/gps/maxphi 360. deg 
/gate/source/twogammapoint1/gps/centre 0.0 0.0 0.0 cm
/gate/source/list

#	V E R B O S I T Y
#/gate/verbose Physic    0
#/gate/verbose Cuts      0
#/gate/verbose Actor     0
#/gate/verbose SD        0
#/gate/verbose Actions   0
#/gate/verbose Step      0
#/gate/verbose Error     0
#/gate/verbose Warning   0
#/gate/verbose Output    0
#/gate/verbose Core      0

/run/verbose 0
/event/verbose 0
/tracking/verbose 0

#	O U T P U T 

#/gate/output/allowNoOutput
/gate/output/ascii/enable
/gate/output/ascii/setFileName Sino_test1
/gate/output/ascii/setOutFileHitsFlag 0
/gate/output/ascii/setOutFileSinglesFlag 0
/gate/output/ascii/setOutFileCoincidencesFlag 0
#/gate/output/ascii/setRootDelayFlag 1
#/gate/output/ascii/setSingleMask 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0

#/gate/output/BasicROOT/setFileName  test3

/gate/output/root/enable
/gate/output/root/setFileName test2
/gate/output/root/setRootHitFlag 0
/gate/output/root/setRootSinglesFlag 1
/gate/output/root/setRootCoincidencesFlag 1
/gate/output/root/setRootdelayFlag 1


#   R A N D O M
# JamesRandom Ranlux64 MersenneTwister
/gate/random/setEngineName JamesRandom
#/gate/random/setEngineSeed default
/gate/random/setEngineSeed auto
#/gate/random/setEngineSeed 123456789
#/gate/random/resetEngineFrom fileName
/gate/random/verbose 1

#	S T A R T 
/gate/application/setTimeSlice     30. s
/gate/application/setTimeStart     0. s
/gate/application/setTimeStop      30. s
/gate/application/startDAQ

