/vis/open OGLSX
/vis/viewer/reset
/vis/viewer/set/viewpointThetaPhi 60 60
/vis/viewer/zoom 1
/vis/viewer/set/style surface
/vis/drawVolume
/tracking/storeTrajectory 1
/vis/scene/endOfEventAction accumulate
/vis/viewer/update

/gate/geometry/setMaterialDatabase /home/ratcap/Simulation/gate/gate_v7.1
/gate/world/geometry/setXLength 100. cm
/gate/world/geometry/setYLength 100. cm
/gate/world/geometry/setZLength 100. cm

#SYSTEM
/gate/world/daughters/name cylindricalPET
/gate/world/daughters/insert cylinder
/gate/cylindricalPET/setMaterial Water
/gate/cylindricalPET/placement/setTranslation 0.0 0.0 0.0 mm
/gate/cylindricalPET/placement/alignToY
/gate/cylindricalPET/geometry/setRmax 350 mm
/gate/cylindricalPET/geometry/setRmin 328 mm
/gate/cylindricalPET/geometry/setHeight 260 mm
/gate/cylindricalPET/vis/forceWireframe

/gate/world/daughters/name phantom
/gate/world/daughters/insert cylinder
/gate/phantom/setMaterial Water
/gate/phantom/placement/setTranslation 0.0 0.0 0.0 mm
/gate/phantom/placement/alignToY
/gate/phantom/vis/forceWireframe
/gate/phantom/geometry/setRmax   17.5 cm
/gate/phantom/geometry/setHeight 30. cm

#     FIRST LEVEL OF THE SYSTEM
/gate/cylindricalPET/daughters/name rsector
/gate/cylindricalPET/daughters/insert box
/gate/rsector/placement/setTranslation 339 0 0 mm
/gate/rsector/geometry/setXLength 20 mm
/gate/rsector/geometry/setYLength 32 mm
/gate/rsector/geometry/setZLength 260 mm
/gate/rsector/setMaterial Air
/gate/rsector/vis/forceWireframe

#     SECOND LEVEL OF THE SYSTEM
/gate/rsector/daughters/name module
/gate/rsector/daughters/insert box
/gate/module/placement/setTranslation 0 0 0 mm
/gate/module/geometry/setXLength 20 mm
/gate/module/geometry/setYLength 32 mm
/gate/module/geometry/setZLength 32 mm
/gate/module/setMaterial Air
/gate/module/vis/setColor yellow
/gate/module/vis/forceWireframe

#     THIRD LEVEL OF THE SYSTEM
/gate/module/daughters/name crystal
/gate/module/daughters/insert box
/gate/crystal/geometry/setXLength 20 mm
/gate/crystal/geometry/setYLength 3.9 mm
/gate/crystal/geometry/setZLength 3.9 mm
/gate/crystal/setMaterial Air
/gate/crystal/vis/setColor red
/gate/crystal/vis/forceWireframe

#      Layer
/gate/crystal/daughters/name LSO
/gate/crystal/daughters/insert box
/gate/LSO/placement/setTranslation 0 0 0 mm
/gate/LSO/geometry/setXLength 20 mm
/gate/LSO/geometry/setYLength 3.9 mm
/gate/LSO/geometry/setZLength 3.9 mm
/gate/LSO/setMaterial LSO

#      R E P E A T    C R Y S T A L
/gate/crystal/repeaters/insert cubicArray
/gate/crystal/cubicArray/setRepeatNumberX 1
/gate/crystal/cubicArray/setRepeatNumberY 8
/gate/crystal/cubicArray/setRepeatNumberZ 8
/gate/crystal/cubicArray/setRepeatVector 0.0 4 4 mm

#       R E P E A T    M O D U L E
/gate/module/repeaters/insert linear
/gate/module/linear/setRepeatNumber 8
/gate/module/linear/setRepeatVector 0. 0. 32.3 mm

#	R E P E A T    R S E C T O R 
/gate/rsector/repeaters/insert ring
/gate/rsector/ring/setRepeatNumber 56

#	A T T A C H    S Y S T E M 
/gate/systems/cylindricalPET/rsector/attach rsector
/gate/systems/cylindricalPET/module/attach module
/gate/systems/cylindricalPET/crystal/attach crystal
/gate/systems/cylindricalPET/layer0/attach LSO

#	A T T A C H    C R Y S T A L  SD
/gate/LSO/attachCrystalSD
/vis/viewer/zoom 2

#	A T T A C H    P H A N T O M  SD
/gate/phantom/attachPhantomSD


#       P H Y S I C S
#
/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel

/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel StandardModel

/gate/physics/addProcess RayleighScattering 
/gate/physics/processes/RayleighScattering/setModel LivermoreModel

/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
/gate/physics/processes/ElectronIonisation/setModel StandardModel e+

/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+

/gate/physics/addProcess PositronAnnihilation

/gate/physics/addProcess eMultipleScattering
/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e- distanceToBoundary
/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e+ distanceToBoundary

/gate/physics/addProcess RadioactiveDecay

/gate/physics/processList Enabled
/gate/physics/processList Initialized


#CUT X , DELTA AND ELECTRON
#/gate/physics/setXRayCut 10 keV
#/gate/physics/setDeltaRayCut 10 keV
#/gate/physics/setElectronCut 2 mm

# INITIALIZE
/gate/run/initialize

#       DIGITIZER
/gate/digitizer/Singles/insert adder 
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setDepth 2

#	TEMPORAL RESOLUTION
/gate/digitizer/Singles/insert timeResolution
/gate/digitizer/Singles/timeResolution/setTimeResolution 2.93 ns

# ENERGY BLURRING
/gate/digitizer/Singles/insert blurring
/gate/digitizer/Singles/blurring/setResolution 0.145
/gate/digitizer/Singles/blurring/setEnergyOfReference 511. keV 

# ENERGY WINDOW
/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 430. keV
/gate/digitizer/Singles/insert upholder
/gate/digitizer/Singles/upholder/setUphold 610. keV 

# DEAD TIME
/gate/digitizer/Singles/insert deadtime
/gate/digitizer/Singles/deadtime/setDeadTime 80. ns
/gate/digitizer/Singles/deadtime/setMode nonparalysable
/gate/digitizer/Singles/deadtime/chooseDTVolume module

#	C O I N C I D E N C E S O R T E R
/gate/digitizer/Coincidences/setWindow 5.86 ns 
/gate/digitizer/Coincidences/setOffset 0. ns
/gate/digitizer/Coincidences/setDepth 3
/gate/digitizer/Coincidences/MultiplesPolicy killAll

/gate/digitizer/name delay
/gate/digitizer/insert coincidenceSorter
/gate/digitizer/delay/setWindow 20. ns
/gate/digitizer/delay/setOffset 500. ns

# Phantom
# 0.1 uCi/cm³ = 249 MBq
/gate/source/addSource linesource
/gate/source/linesource/setActivity 1500000. becquerel
/gate/source/linesource/setType backtoback
/gate/source/linesource/gps/particle gamma
/gate/source/linesource/gps/energytype Mono
/gate/source/linesource/gps/monoenergy 0.511 MeV
/gate/source/linesource/gps/angtype iso 
/gate/source/linesource/gps/mintheta 0. deg 
/gate/source/linesource/gps/maxtheta 180. deg 
/gate/source/linesource/gps/minphi 0. deg 
/gate/source/linesource/gps/maxphi 360. deg 
/gate/source/linesource/gps/type Volume 
/gate/source/linesource/gps/shape Cylinder 
/gate/source/linesource/gps/radius 17.5. cm 
/gate/source/linesource/gps/halfz 35. cm 

#O U T P U T
#ASCII
#/gate/output/ascii/enable
#/gate/output/ascii/setFileName output_mMR
#/gate/output/ascii/setOutFileHitsFlag 0
#/gate/output/ascii/setOutFileSinglesFlag 1
#/gate/output/ascii/setOutFileCoincidencesFlag 1
#
#ROOT
/gate/output/root/enable
/gate/output/root/setFileName root_output_mMR
/gate/output/root/setRootNtupleFlag 1
/gate/output/root/setRootHitFlag 0
/gate/output/root/setRootSinglesFlag 1
/gate/output/root/setRootCoincidencesFlag 1
/gate/output/root/setSaveRndmFlag 1
#LMF
#/gate/output/lmf/disable
#

#   R A N D O M
# JamesRandom Ranlux64 MersenneTwister
/gate/random/setEngineName JamesRandom
#/gate/random/setEngineSeed default
/gate/random/setEngineSeed auto
#/gate/random/setEngineSeed 123456789
#/gate/random/resetEngineFrom fileName
/gate/random/verbose 1

#S T A R T
/gate/application/setTimeSlice 30. s
/gate/application/setTimeStart 0. s
/gate/application/setTimeStop 30 s
/gate/application/startDAQ

exit

