

# TASK
# DEFINE A ROOT LISTMODE FILE OUTPUT
# STORE SINGLE, COINCIDENCE AND RANDOM EVENTS

/gate/output/root/enable
/gate/output/root/setFileName             output/YourRootFile

/gate/output/root/setRootHitFlag          0
/gate/output/root/setRootSinglesFlag      1
/gate/output/root/setRootCoincidencesFlag 1
/gate/output/root/setRootdelayFlag        1
/gate/output/root/setRootNtupleFlag       0

# TASK
# DEFINE A RAW SINOGRAM OUTPUT
# APPLY A SPATIAL BLURRING (2 MM FWHM)
# STORE THE TRUE COINCIDENCES

/gate/output/sinogram/enable
/gate/output/sinogram/setFileName output/YourSinogram	
/gate/output/sinogram/RawOutputEnable yes

#/gate/output/sinogram/setTangCrystalBlurring 2 mm
#/gate/output/sinogram/setAxialCrystalBlurring 2 mm
/gate/output/sinogram/setInputDataName Coincidences
/gate/output/sinogram/TruesOnly
#/gate/output/sinogram/StoreDelayeds
#/gate/output/sinogram/StoreScatters
/gate/output/sinogram/verbose 1
/gate/output/sinogram/describe

