!INTERFILE  :=
!imaging modality := PT
name of data file := Proj_VP_linesource.s
originating system := VersaPET
!version of keys := STIR3.0
!GENERAL DATA :=
!GENERAL IMAGE DATA :=
!type of data := PET
imagedata byte order := LITTLEENDIAN
!PET STUDY (General) :=
!PET data type := Emission
applied corrections := {NONE}
!number format := float
!number of bytes per pixel := 4
number of dimensions := 4
matrix axis label [4] := segment
!matrix size [4] := 31
matrix axis label [3] := view
!matrix size [3] := 96
matrix axis label [2] := axial coordinate
!matrix size [2] := { 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1}
matrix axis label [1] := tangential coordinate
!matrix size [1] := 191
minimum ring difference per segment := { -15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15}
maximum ring difference per segment := { -15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15}
Scanner parameters:= 
Scanner type := VersaPET
Number of rings                          := 16
Number of detectors per ring             := 192
Inner ring diameter (cm)                 := 15.29
Average depth of interaction (cm)        := 0.6
Distance between rings (cm)              := 0.24
Default bin size (cm)                    := 0.12
View offset (degrees)                    := 0
Maximum number of non-arc-corrected bins := 191
Default number of arc-corrected bins     := 191
Number of blocks per bucket in transaxial direction         := 1
Number of blocks per bucket in axial direction              := 4
Number of crystals per block in axial direction             := 4
Number of crystals per block in transaxial direction        := 8
Number of detector layers                                   := 1
Number of crystals per singles unit in axial direction      := 1
Number of crystals per singles unit in transaxial direction := 1
end scanner parameters:=
effective central bin size (cm) := 0.12
number of time frames := 1
!END OF INTERFILE :=
