
#=====================================================
# PHYSICAL PROCESSES
#=====================================================

/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel

/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel StandardModel

/gate/physics/addProcess RayleighScattering
/gate/physics/processes/RayleighScattering/setModel PenelopeModel

/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
/gate/physics/processes/ElectronIonisation/setModel StandardModel e+

/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+

/gate/physics/addProcess PositronAnnihilation

#/gate/physics/addProcess eMultipleScattering e+
#/gate/physics/addProcess eMultipleScattering e-

/gate/physics/addProcess eMultipleScattering
/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e- distanceToBoundary
/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e+ distanceToBoundary

/gate/physics/addProcess RadioactiveDecay

/gate/physics/processList Enabled
/gate/physics/processList Initialized

#=====================================================
# CUTS
#=====================================================

# TASK
# DEFINE A CUT VALUE TO LIMIT THE PRODUCTION OF 
# SECONDARY PHOTON AND ELECTRON IN THE DETECTOR
#
#/gate/physics/Gamma/SetCutInRegion      crystalUnit 1.0 cm
#/gate/physics/Electron/SetCutInRegion   crystalUnit 1.0 cm

#/gate/physics/setXRayCut 10 keV
#/gate/physics/setDeltaRayCut 10 keV
#/gate/physics/setElectronCut 2 mm



